version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - ./.env:/app/.env
    environment:
      - DB_URL=sqlite:///./data/scraps.db
      - CHAT_API_BASE=http://host.docker.internal:1234/v1
      - CHAT_MODEL=gpt-4o-mini-compat-or-your-local
      - EMBED_API_BASE=http://host.docker.internal:1234/v1
      - EMBED_MODEL=text-embedding-3-large-or-nomic-embed-text
      - TIMEOUT_SEC=30
    depends_on:
      - lmstudio
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # LM Studio service (external)
  # Note: This requires LM Studio to be running on the host
  # Alternatively, you can use Ollama:
  
  # ollama:
  #   image: ollama/ollama:latest
  #   ports:
  #     - "11434:11434"
  #   volumes:
  #     - ollama_data:/root/.ollama
  #   restart: unless-stopped

# volumes:
#   ollama_data: