name: Browser tests (manual)

on:
  workflow_dispatch: {}

jobs:
  browser-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Install Playwright system dependencies and fonts
        run: |
          sudo apt-get update
          sudo apt-get install -y libnss3 libatk-bridge2.0-0 libatk1.0-0 libcups2 libxss1 libgbm1 libasound2 fonts-noto-cjk

      - name: Install Playwright and browsers
        run: |
          pip install playwright
          python -m playwright install chromium

      - name: Prepare workspace and test DB
        run: |
          mkdir -p data
          rm -f test.db || true
          sqlite3 test.db "VACUUM;" || true

      - name: Apply SQL migrations
        run: |
          python migrations/apply_migrations.py --db ./test.db

      - name: Run browser tests
        env:
          DB_URL: sqlite:///./test.db
        run: |
          pytest -q -m browser
