name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install pytest playwright
      - name: Install system dependencies for Playwright & fonts
        run: |
          sudo apt-get update
          sudo apt-get install -y libnss3 libatk-bridge2.0-0 libatk1.0-0 libcups2 libxss1 libgbm1 libasound2t64 fonts-noto-cjk
      - name: Install Playwright browsers
        run: |
          python -m playwright install chromium
      - name: Prepare test DB env
        run: |
          mkdir -p data
      - name: Run tests (full)
        env:
          DB_URL: sqlite:///./test.db
        run: pytest -q
