name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Prepare workspace and test DB
        run: |
          mkdir -p data
          rm -f test.db || true
          sqlite3 test.db "VACUUM;" || true

      - name: Apply SQL migrations
        run: |
          python migrations/apply_migrations.py --db ./test.db

      - name: Verify migrations applied
        run: |
          # Ensure core tables exist; fail the job if migrations didn't create them
          echo "Checking for expected tables in test.db"
          missing=0
          for t in documents bookmarks postprocess_jobs; do
            sqlite3 test.db "SELECT name FROM sqlite_master WHERE type='table' AND name='${t}';" | grep -q "${t}" || missing=1
          done
          if [ "$missing" -ne 0 ]; then
            echo "ERROR: One or more expected tables are missing after migrations"
            sqlite3 test.db ".schema" || true
            exit 1
          fi

      - name: Run tests
        env:
          DB_URL: sqlite:///./test.db
        run: |
          pytest -q -m "not browser"
      
      # Browser tests are intentionally not run on push/PR to keep CI fast.
