name: Python CI

on:
  push:
    branches: [ main, '**/feat/*', '**/chore/*' ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.11, 3.12]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      env:
        PYTHONPATH: .
      run: |
        pytest -q

    - name: Upload coverage (optional)
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: pytest-logs
        path: .
